name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ProjectRoomManager/ProjectRoomManager.sln
    - name: Build
      run: dotnet build ProjectRoomManager/ProjectRoomManager.sln --no-restore
    - name: Test
      run: dotnet test ProjectRoomManager/ProjectRoomManager.sln --no-build --verbosity normal
